AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  buy_coin_every_month

  Sample SAM Template for buy_coin_every_month

Parameters:
  GmoCoinApiKey:
    Type: AWS::SSM::Parameter::Value<String>
    Default: 'GMO_COIN_API_KEY'
  GmoCoinSecretKey:
    Type: AWS::SSM::Parameter::Value<String>
    Default: 'GMO_COIN_SECRET_KEY'

Globals:
  Function:
    Timeout: 3

Resources:
  BuyBitcoinFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: buy_bitcoin/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          API_KEY: !Ref GmoCoinApiKey
          SECRET_KEY: !Ref GmoCoinSecretKey
      Events:
        BuyBitcoinMonthly:
          Type: Schedule
          Properties:
            Schedule: cron(00 23 09 * ? *)

Outputs:
  BuyBitcoinFunction:
    Description: "Buy Bitcoin Lambda Function ARN"
    Value: !GetAtt BuyBitcoinFunction.Arn
  BuyBitcoinFunctionIamRole:
    Description: "Implicit IAM Role created for Buy Bitcoin function"
    Value: !GetAtt BuyBitcoinFunctionRole.Arn
